version: "3.0"
services:
  nextflow:
    image: bentsherman/nextflow-gke
    env:
      - NEXTFLOW_K8S=true
    entrypoint:
      - /bin/bash
      - -c
      - cd /opt/nextflow-gke; python3 server.py
    ports:
      - $HOST_PORT:8080
    volumes:
      - $LOCAL_STORE:/workspace
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4Gi
